#!/bin/bash

function handle_interrupt {
    echo "Ctrl+C was pressed. Exiting..."
    pkill -9 dolphin
    pkill -9 ray
    exit 0
}

# Set up the trap to call the function when SIGINT is received
trap handle_interrupt SIGINT

python3 tests.py
pkill -9 dolphin
pkill -9 ray